query($limit: Int!, $skip: Int!) {
	bflBlogPostCollection(limit: $limit, skip: $skip) {
		items {
			title
			slug
			thumbnail {
				url
			}
			excerpt
			content {
				json
			}
			date
			author
		}
	}
}
